presubmits:
  - name: greet-api-deploy
    decorate: true
    clone_uri: "git@github.com:darrensemusemu/skaffold-k8s-example.git"
    # run_if_changed: '^(service.user\/.*)|(\.prow\/service\.user\.yaml)$'
    always_run: true
    skip_report: false
    context: skaffold-k8s-example
    max_concurrency: 1
    spec:
      containers:
        - name: skaffold
          image: "gcr.io/k8s-skaffold/skaffold:v1.38.0"
          command: ["/bin/sh", "-c", "./scripts/skaffold-build-deploy.sh"]
          env:
            - name: CLUSTER_DEV_NAME
              value: main-cluster
            - name: PROJECT_DEV_NAME
              value: darrensemusemu-infra
            - name: PROJECT_DEV_REGION
              value: europe-west1-b
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/skaffold-service-account.json
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: service-account
              mountPath: /secrets
      volumes:
        - name: service-account
          secret:
            secretName: scaffold-service-account
      restartPolicy: Always
    branches:
      - main
    skip_branches: []
